import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#7587a7',
        'background': '#f7f9fc',
        'surface-container-low': '#f2f4f7',
        'on-tertiary-fixed': '#0d1c2e',
        'tertiary-container': '#112032',
        'on-primary-fixed-variant': '#364764',
        'surface': '#f7f9fc',
        'surface-container-highest': '#e0e3e6',
        'surface-container': '#eceef1',
        'error-container': '#ffdad6',
        'secondary-container': '#fea619',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ffb95f',
        'on-error': '#ffffff',
        'on-surface-variant': '#44474d',
        'primary-container': '#0b1f3a',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#d5e3fc',
        'outline-variant': '#c4c6ce',
        'inverse-on-surface': '#eff1f4',
        'on-error-container': '#93000a',
        'tertiary': '#000714',
        'error': '#ba1a1a',
        'outline': '#75777e',
        'on-primary-fixed': '#071c36',
        'secondary': '#855300',
        'on-secondary': '#ffffff',
        'primary': '#000615',
        'surface-variant': '#e0e3e6',
        'on-secondary-fixed-variant': '#653e00',
        'primary-fixed-dim': '#b5c7ea',
        'primary-fixed': '#d6e3ff',
        'tertiary-fixed-dim': '#b9c7df',
        'inverse-primary': '#b5c7ea',
        'on-surface': '#191c1e',
        'on-secondary-container': '#684000',
        'surface-dim': '#d8dadd',
        'inverse-surface': '#2d3133',
        'secondary-fixed': '#ffddb8',
        'on-tertiary-fixed-variant': '#3a485b',
        'on-secondary-fixed': '#2a1700',
        'on-background': '#191c1e',
        'surface-container-high': '#e6e8eb',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#79889e',
        'surface-bright': '#f7f9fc',
        'surface-tint': '#4d5f7d',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
export default config
